### ISSUE TITLE
GMS in F-Droid build

### ISSUE THREAD

**Issue by linsui** [slartus/4pdaClient-plus#116]
It's pulled by `com.evernote:android-job` which is deprecated anyway. Could you please use `androidx.work:work-runtime` instead? Thanks!

**Comment by licaon-kter** [comment]
Can you maybe switch to this fork that's cleaned up maybe? https://github.com/wireapp/android-job/tree/wireapp/v1.2.6-no-gms

**Comment by ildar** [comment]
отлично! thank you!

**Comment by licaon-kter** [comment]
@ildar ping us when released

**Comment by slartus** [comment]
@licaon-kter ping

**Comment by licaon-kter** [comment]
@slartus I see no tags? https://github.com/slartus/4pdaClient-plus/tags

**Comment by slartus** [comment]
@licaon-kter 
sorry
https://github.com/slartus/4pdaClient-plus/releases/tag/3.6.4

**Comment by licaon-kter** [comment]
Done: https://gitlab.com/fdroid/fdroiddata/-/commit/ee63ee20ef74f953ec75785ad6ce4acfcfe84780

And if you bump these 2 before tagging: https://github.com/slartus/4pdaClient-plus/blob/3.6.4/app/build.gradle#L16-L26 autoupdate will work just fine
