### ISSUE TITLE
Нормальная версия приложения на Flutter

### ISSUE THREAD

**Issue by mediaexplorer74** [slartus/4pdaClient-plus#118]
Привет, Артём.
Так понимаю, Вы всю жизнь будете игнорировать Плюсы и Шарпы. Но есть ли в планах сьезд на что-то нормальное, мультиплатформенное типа так любимое дроидостроителями Флаттера?

**Comment by slartus** [comment]
Чииивоооо? Я на шарпе полжизни программировал. На флаттере точно не будет, а вот на  compose multi platform очень может быть

**Comment by mediaexplorer74** [comment]
> Чииивоооо? Я на шарпе полжизни программировал. На флаттере точно не будет, а вот на compose multi platform очень может быть

Пол-жизни? Ух ты! А на Гитхабе 0 репок (репозиториев), как-то удивительно ;)
Что ж, тогда сорян, простите очкарика )
Скажите, пожалуйста, а не осталось ли каких-нить драфтов, заготовок 4PDA на Шарпах? Была у меня года два назад ну хоть лайтовенький клиент для старушки (мобилки-винфончика) Люмка замутить ) Я весь Гитхаб излазал, ну вообще нет заготовок, словно никто никогда ничего не делал для 4PDA 
Вот бы на Уно или Замарин Формс мультиплатформу замутить ) Мечты, конеш! Вашу штуковину, думаю, мне с Явы слабо будет конвернтуть на Шарпы

**Comment by slartus** [comment]
Винфон никогда не уважал, поэтому ничего под него не писал. Заготовок нет

**Comment by mediaexplorer74** [comment]
> Винфон никогда не уважал, поэтому ничего под него не писал. Заготовок нет

Там обычный UWP. Такой же, как на Игрокоробке XBOX по сути

**Comment by mediaexplorer74** [comment]
> Винфон никогда не уважал, поэтому ничего под него не писал. Заготовок нет

C 2023им, наступившим по всем стилям. Как дела с compose multi platform, планы в силе? 
Сам вот простенькое UWP-приложение 4PDAClient сделал, чисто на веб-вьюшке (ну еще js-иньекции использую для +/- шрифта) . Тема на форуме 4PDA в разделе WindowsPhone давно заблочена (кто-то лет 5 назад до меня уже че-то подобное для WP8.1 делал), так что на форум выкладывать ничего выложено мною не будет. Кому интересно, зайдут на ГитХаб, найдут через поиск.

**Comment by slartus** [comment]
И тебя с прошедшим. Планы в силе, но они не скоро будут реализованы. сначала надо переписать существующий функционал под архитектуру, которая позволит на мультиплатформу писать
