### ISSUE TITLE
Не хватает кнопок для перехода по страницам в новостях

### ISSUE THREAD

**Issue by teod0r** [slartus/4pdaClient-plus#23]
Было бы удобно, если б были кнопки для навигации по страницам в новостях.

Недавно установил программу и читаю новости. Свежие новости прочитал, читаю старые. Приходится вручную много пркручивать вниз после рестарта программы, например, после ребута устройства. Было бы удобнее переходить на определённую страницу.

**Comment by slartus** [comment]
не надо в issues хотелки пихать
