### ISSUE TITLE
create tags for releases

### ISSUE THREAD

**Issue by ildar** [slartus/4pdaClient-plus#24]
Прошу создавать тэги при каждом релизе. Без них на F-Droid сборку не запускают. В итоге там старые версии.
Спасибо. Ожидаю тег для последней версии.

**Comment by ildar** [comment]
Напоминаю!
Опять без новых версий...

**Comment by ildar** [comment]
Это критично!
Поскольку текущая версия в F-droid больше не работает!

**Comment by ildar** [comment]
@radiationx ?

**Comment by RadiationX** [comment]
Ok
