### ISSUE TITLE
Performance improvement suggestion

### ISSUE THREAD

**Issue by struggggle** [slartus/4pdaClient-plus#25]
Dear developers,
I found several bitmap displaying issues in 4pdaClient. These issues could affect performance. 
In the position of 4pdaClient:
org.softeg.slartus.forpdaplus.classes.common.ExtBitmap.java     getBitmapFromAsset ()
the bitmap object is created with the invocation of decodeStream(). 
I found getBitmapFromAsset() is invoked indirectly by:
org.softeg.slartus.forpdaplus.classes.BbCodesBasePanel.java    getView()
getView() callbacks are frequently invoked in the UI thread and this means that there will be many bitmap objects being created.
Since image decoding is slow, for performance considerations, we should perform the image decoding operations in worker threads (e.g., via AsyncTask).

In addition, maybe we can define memory cache and disk memory cache to store the bitmap objects. Then app can reuse them instead of creating new bitmap objects continuously. Also, we can use the Option.inbitmap to reuse the memory space of existing bitmap objects, which will greatly reduce the memory consumption and improves app's performance.

By the way, for bitmap displaying, I was wondering why you do not use third-party libraries here? I noticed that universal image loader and picasso are used in 4pdaClient. Would you mind sharing some thoughts?
Looking forward to your response and hope I can help improve 4pdaClient.
Thanks.

References: 
https://developer.android.com/training/displaying-bitmaps/process-bitmap.html
https://developer.android.com/training/displaying-bitmaps/cache-bitmap.html
the use of inbitmap: 
https://www.youtube.com/watch?v=_ioFW3cyRV0&list=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE&index=54
https://developer.android.com/training/displaying-bitmaps/manage-memory.html

**Comment by iSanechek** [comment]
Hi @struggggle. Thanks for you replay. We are aware of this issue and working on it. In the next major update this will be fixed.
