### ISSUE TITLE
Incompatible API use in your codes

### ISSUE THREAD

**Issue by jay2013** [slartus/4pdaClient-plus#27]
Hi,
We notice that in your codes you use API like "<org.apache.http.cookie.Cookie: java.lang.String getName()>" and "<org.apache.http.conn.scheme.SchemeRegistry: org.apache.http.conn.scheme.Scheme register(org.apache.http.conn.scheme.Scheme)>"  which are already removed after SDK level 23. These API use are very likely to cause crash to your app because the minSDKVersion of your APP is 15.

There are exist reachable path from your code to these api. For example, the reachable path to the first API we mentioned above is:
<org.softeg.slartus.forpdaplus.MainActivity: void onNewIntent(android.content.Intent)>
		--><org.softeg.slartus.forpdaplus.MainActivity: boolean checkIntent(android.content.Intent)>
		--><org.softeg.slartus.forpdaplus.IntentActivity: java.lang.Boolean tryShowUrl(android.app.Activity,android.os.Handler,java.lang.String,java.lang.Boolean,java.lang.Boolean)>
		--><org.softeg.slartus.forpdaplus.IntentActivity: java.lang.Boolean tryShowUrl(android.app.Activity,android.os.Handler,java.lang.String,java.lang.Boolean,java.lang.Boolean,java.lang.String)>
		--><org.softeg.slartus.forpdaplus.IntentActivity: boolean tryShowFile(android.app.Activity,android.net.Uri,java.lang.Boolean)>
		--><org.softeg.slartus.forpdaplus.Client: java.lang.Boolean hasLoginCookies()>
               --><org.apache.http.cookie.Cookie: java.lang.String getName()>

We use android studio to analyze your app's apk file, and we also find methods in org.apache.http.cookie.Cookie don't have definition, they are all referenced methods which need android platform to support.
![org softeg slartus forpdaplus](https://user-images.githubusercontent.com/4310866/38164288-7a7c28b0-3534-11e8-8df2-d7c3d51b4f04.png)

more similar bugs, please refer to this file below.
[org.softeg.slartus.forpdaplus_596.apk.txt](https://github.com/slartus/4pdaClient-plus/files/1865567/org.softeg.slartus.forpdaplus_596.apk.txt)

We cannot make 100% sure about the reachable path, so we need your help to check whether it is reachable from your code to these unsupported API. Thanks very much.

best regards,

Dongjie He

**Comment by slartus** [comment]
fixed
