### ISSUE TITLE
Start tagging releases again

### ISSUE THREAD

**Issue by krt16s** [slartus/4pdaClient-plus#4]
While releases were tagged until 2.5.1, recent versions don't have tags. Maybe your forgot to `git --push` them. Could you add tags, again?

**Comment by krt16s** [comment]
2.5.6 is tagged again, closing.

**Comment by krt16s** [comment]
No tags since 3.0.1.. what a pity..

**Comment by ildar** [comment]
@slartus ? Пожалуйста, тэгните релиз. Ато из F-Droid версия не ничего не показывает! (без специальных движений)

**Comment by ildar** [comment]
@krt16s , I see the 3.2.2 tag. Is it allright for build?
