### ISSUE TITLE
F-Droid build is outdated

### ISSUE THREAD

**Issue by dimqua** [slartus/4pdaClient-plus#56]
Для того, чтобы обеспечить автоматические обновления на F-Droid, необходимо использовать числовые значения `VersionCode` и `VersionName` [вот здесь](https://github.com/slartus/4pdaClient-plus/blob/3.5.4/app/build.gradle#L32). Возможно ли это?

UPD. Уже обновили, но пришлось пинать маинтейнеров, в будущем хотелось бы этого избежать.

**Comment by slartus** [comment]
VersionName никогда и нигде не делают числовым. у нас это 3.5.4
VersionCode не может быть НЕ числовым.

**Comment by dimqua** [comment]
Да, глупость сказал. Имел ввиду статические значения, а не переменные, то есть:
```
versionCode = 621
versionName = "3.5.4"
```

**Comment by licaon-kter** [comment]
I've disabled autoupdate as Tags and versionName never match.

Ref:https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6464/diffs#diff-content-0ed24dc645488fecf604c207715f5637dba5facf

**Comment by ildar** [comment]
Давайте переоткроем
